/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;
import classes.BethesdaStudio;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
/**
 *
 * @author Sebastian Rodriguez
 */
public class Bethesda extends javax.swing.JPanel {
    private int valorSpinner; // Declarar como miembro de la clase

    public Bethesda() {
        initComponents();
    
        // Obtén el valor inicial del JSpinner
        valorSpinner = (int) spinnnerNarrativaB.getValue();
        if (valorSpinner == 1){
            // Llama a la función para crear un desarrollador de narrativa
                    BethesdaStudio.crearDesarrolladorNarrativa(BethesdaStudio.driveN, 0, 4);
        }
            
        // Agrega un ChangeListener al JSpinner
        spinnnerNarrativaB.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                // Obtén el nuevo valor del JSpinner
                int nuevoValorSpinner = (int) spinnnerNarrativaB.getValue();
                
                // Compara el nuevo valor del JSpinner con valorSpinner
                if (nuevoValorSpinner > valorSpinner) {
                    //FUNCION CREAR DESARROLLADOR NARRATIVA
                    // Llama a la función para crear un desarrollador de narrativa
                    BethesdaStudio.crearDesarrolladorNarrativa(BethesdaStudio.driveN, 0, 4);
                    // Resta 1 a desarrolladoresRestantesB si el nuevo valor es mayor
                    int valorActual = Integer.parseInt(desarrolladoresRestantesB.getText());
                    valorActual--;
                    desarrolladoresRestantesB.setText(Integer.toString(valorActual));
                } else if (nuevoValorSpinner < valorSpinner) {
                    //FUNCION STOP DESARROLLADOR NARRATIVA
                    BethesdaStudio.stopDesarrolladorNarrativaAleatorio();
                    // Suma 1 a desarrolladoresRestantesB si el nuevo valor es menor
                    int valorActual = Integer.parseInt(desarrolladoresRestantesB.getText());
                    valorActual++;
                    desarrolladoresRestantesB.setText(Integer.toString(valorActual));
                }
                
                // Actualiza valorSpinner con el nuevo valor del JSpinner
                valorSpinner = nuevoValorSpinner;
            }
        });
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        desarrolladoresRestantesB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnnerNarrativaB = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        guionesEnDriveB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(720, 603));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Bethesda");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, 68));

        jLabel2.setText("Desarrolladores restantes = ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        desarrolladoresRestantesB.setText("14");
        add(desarrolladoresRestantesB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel3.setText("Narrativa = ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, -1));

        spinnnerNarrativaB.setModel(new javax.swing.SpinnerNumberModel(1, 1, 11, 1));
        spinnnerNarrativaB.setValue(1);
        add(spinnnerNarrativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel4.setText("Capacidad Drive");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        guionesEnDriveB.setText("0");
        add(guionesEnDriveB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 30, -1));

        jLabel6.setText("de 25");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getDesarrolladoresRestantesB() {
        return desarrolladoresRestantesB;
    }

    public void setDesarrolladoresRestantesB(JLabel desarrolladoresRestantesB) {
        this.desarrolladoresRestantesB = desarrolladoresRestantesB;
    }

    public static JLabel getGuionesEnDriveB() {
        return guionesEnDriveB;
    }

    public void setGuionesEnDriveB(JLabel guionesEnDriveB) {
        this.guionesEnDriveB = guionesEnDriveB;
    }
    public static void actualizarGuionesEnDrive(int nuevoValor) {
    guionesEnDriveB.setText(Integer.toString(nuevoValor));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desarrolladoresRestantesB;
    public static javax.swing.JLabel guionesEnDriveB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnnerNarrativaB;
    // End of variables declaration//GEN-END:variables
}
